server:
  port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        output:
          destination: events
          contentType: application/json
