server:
  port: 8888

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        input:
          destination: events
          contentType: application/json
          group: sink
        output:
          destination: events
          contentType: application/json