version: '3.1'

services:
  test-condition:
    build: ./
    ports:
      - 8888:8888

  zookeeper:
    image: zookeeper:3.4.14

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
