server:
  port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        input:
          destination: events
          group: demo
        output:
          destination: events
          group: demo
