version: '3.1'

services:
  sink:
    build: ./simple-events-sink
    ports:
      - 8888:8888
    links:
      - kafka

  source:
    build: ./simple-events-source
    ports:
      - 8080:8080
    links:
      - kafka

  zookeeper:
    image: debezium/zookeeper:0.8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:0.8
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
